# Generated by Django 4.2.16 on 2024-11-25 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_news_keyword'),
        ('accounts', '0002_remove_user_nickname_user_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useractivity',
            unique_together={('news', 'user', 'action_type')},
        ),
    ]
