# Generated by Django 4.2.16 on 2024-11-25 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_useractivity_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
