# Generated by Django 4.2.16 on 2024-11-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_useractivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='disliked_categories',
        ),
        migrations.AddField(
            model_name='profile',
            name='disliked_categories',
            field=models.JSONField(default=list),
        ),
    ]
