# Generated by Django 4.2.16 on 2024-11-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_profile_disliked_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='disliked_categories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
