# Generated by Django 4.2.16 on 2024-11-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_sentiment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediacompany',
            name='company_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
