# Generated by Django 4.2.16 on 2024-11-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_mediacompany_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='article_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
