# Generated by Django 4.2.16 on 2024-11-21 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_article_id_news_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='news_title',
            new_name='title',
        ),
    ]
