# Generated by Django 4.2.16 on 2024-11-21 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_rename_news_title_news_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediacompany',
            old_name='name',
            new_name='comapany_name',
        ),
    ]
