# Generated by Django 4.2.16 on 2024-11-21 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_rename_name_mediacompany_comapany_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='id',
        ),
        migrations.AlterField(
            model_name='news',
            name='article_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
