# Generated by Django 4.2.16 on 2024-11-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_rename_comapany_name_mediacompany_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediacompany',
            name='id',
        ),
        migrations.AlterField(
            model_name='mediacompany',
            name='company_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
