# Generated by Django 4.2.16 on 2024-11-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_remove_mediacompany_id_alter_mediacompany_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='keyword',
            field=models.TextField(blank=True, null=True),
        ),
    ]
